### ISSUE TITLE
npmunbox does not work offline with npm version 1.4.15

### ISSUE THREAD

**Issue by davidslater250** [arei/npmbox#16]
Looks like new versions on npm require a connection for install.
Turning off my connection and running npmunbox karma.npmbox results in:

$ npmunbox -v karma.npmbox
Extracting archive karma...
Installing karma...
info trying registry request attempt 1 at 11:53:06
http GET https://registry.npmjs.org/karma
info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND
info trying registry request attempt 2 at 11:53:06
http GET https://registry.npmjs.org/karma
info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND
info trying registry request attempt 3 at 11:53:06
http GET https://registry.npmjs.org/karma

Cleaning Up...

npmunbox had the following errors...
  Unable to install karma.npmbox from karma

**Comment by yccteam** [comment]
I'm getting this error as well, when trying to install karma-jasmin and karma-requirejs. I'm using the 2.1.2, nodejs 0.10.38 and npm 1.4.28

**Comment by arei** [comment]
@yccteam can you create a new issue for this? When you do so, please include a log file with the verbose output, the OS, the versions, etc.

**Comment by yccteam** [comment]
It's a bit hard, since the computer involved is offline and there are no means to take data out of it.

**Comment by yccteam** [comment]
Ok, it might be my npm version. It's 1.4.28... quite old.
Do you know how I can update an npm version on an offline computer? Do I just replace the files?
I tried to box/unbox, but it has its own errors.

**Comment by arei** [comment]
Try the version I just published.  I shrinkwrapped the dependencies, which
might help.

**Comment by arei** [comment]
The new version shrinkwraps the latest npm with it and uses that.  Of course, you would need to reinstall npmbox on the offline machine first.

**Comment by yccteam** [comment]
I'm working on getting the verbose data approved. I'll let you know once it's done.
