### ISSUE TITLE
Installing npmbox offline yields TypeError: Cannot call method 'replace' of null

### ISSUE THREAD

**Issue by MrOnosa** [arei/npmbox#18]
I successfully untar'd the npmbox.npmbox file on my server, but the following command

     npm install --global --cache ./.npmbox-cache --optional --no-registry --fetch-retries 0 --fetch-retry-factor 0 --fetch-retry-mintimeout 1 --fetch-retry-maxtimeout 2 npmbox

yields the following results

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   '--no-registry',
1 verbose cli   '--fetch-retries',
1 verbose cli   '0',
1 verbose cli   '--fetch-retry-factor',
1 verbose cli   '0',
1 verbose cli   '--fetch-retry-mintimeout',
1 verbose cli   '1',
1 verbose cli   '--fetch-retry-maxtimeout',
1 verbose cli   '2',
1 verbose cli   'npmbox' ]
2 info using npm@1.4.14
3 info using node@v0.10.29
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 verbose cache add [ 'npmbox', null ]
6 verbose cache add name=undefined spec="npmbox" args=["npmbox",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'npmbox',
7 verbose parsed url   path: 'npmbox',
7 verbose parsed url   href: 'npmbox' }
8 silly lockFile f93a988d-npmbox npmbox
9 verbose lock npmbox C:\Users\Tp\AppData\Roaming\npm-cache\f93a988d-npmbox.lock
10 silly lockFile f93a988d-npmbox npmbox
11 silly lockFile f93a988d-npmbox npmbox
12 verbose addNamed [ 'npmbox', '' ]
13 verbose addNamed [ null, '*' ]
14 silly lockFile 685b8df2-npmbox npmbox@
15 verbose lock npmbox@ C:\Users\Tp\AppData\Roaming\npm-cache\685b8df2-npmbox.lock
16 silly addNameRange { name: 'npmbox', range: '*', hasData: false }
17 error TypeError: Cannot call method 'replace' of null
17 error     at cf (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-cache-filename\index.js:11:18)
17 error     at RegClient.get (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:24:20)
17 error     at addNameRange (C:\Program Files (x86)\nodejs\node_modules\npm\lib\cache\add-named.js:198:12)
17 error     at C:\Program Files (x86)\nodejs\node_modules\npm\lib\cache\add-named.js:47:5
17 error     at C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\locker.js:30:7
17 error     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\lockfile\lockfile.js:143:23
17 error     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\lockfile\lockfile.js:143:23
17 error     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\lockfile\lockfile.js:143:23
17 error     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\lockfile\lockfile.js:143:23
17 error     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\lockfile\lockfile.js:143:23
18 error If you need help, you may report this *entire* log,
18 error including the npm and node versions, at:
18 error     <http://github.com/npm/npm/issues>
19 error System Windows_NT 6.1.7601
20 error command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "--no-registry" "--fetch-retries" "0" "--fetch-retry-factor" "0" "--fetch-retry-mintimeout" "1" "--fetch-retry-maxtimeout" "2" "npmbox"
21 error cwd u:\
22 error node -v v0.10.29
23 error npm -v 1.4.14
24 error type non_object_property_call
25 verbose exit [ 1, true ]

**Comment by arei** [comment]
I believe this to be an error in npm itself.  Please download the new version and try again.
