### ISSUE TITLE
Make npmbox work simultaneously

### ISSUE THREAD

**Issue by arei** [arei/npmbox#2]
If you run npmbox at the same time as another npmbox, the two will try to use the same directory (.npmbox-cache) which could cause conflicts.  However, npmunbox requires that npmbox use this naming convention.

npmbox needs to use a temporary name structure when downloading the packages and then convert the name as it is being written into the .npmbox file so as to not create overlaps.

**Comment by danfuzz** [comment]
This is fixed in master and should be published soon (within a day or so).

**Comment by danfuzz** [comment]
Fixed in v4.2.0, just published.
