### ISSUE TITLE
not support windows?

### ISSUE THREAD

**Issue by tanbamboo** [arei/npmbox#21]
Windows 7 x64
npm 1.4.28
node 0.10.33

error when install npmbox from the .npmbox-cache, the output log looks like:
npm ERR! not a package C:\Users\.....\tmp.tgz

**Comment by fraballi** [comment]
Is there any step-by-step that comprises Windows as the platform of use? I read the 'npmbox' docs and nothing works for windows apparently? Exists any possibility of calling: npmbox as a PATH registered variable, as 'npm' works?

**Comment by arei** [comment]
@tanbamboo I am unable to duplicate your issues as described here, although I do not have a mac like you were using to test this on either. npmbox works fine for me on Win7 for both sides of the operation (npmbox and npmunbox).  Don't know what else to tell you...

It is possible that this is related to the mac/linux using a `/` for a path character and windows using a `\`.  Perhaps something in the 7zip/tar process could help address this?

Also, I did just publish a new version and you could always try that out.

**Comment by tanbamboo** [comment]
@arei Thanks, I will try the new version.
