### ISSUE TITLE
Unable to install gulp.npmbox from gulp

### ISSUE THREAD

**Issue by zongliangding** [arei/npmbox#22]
Hello, can I install gulp in Windows 7 with offline environment with npmbox? 

I can install other package except this one, the error message is : Unable to install gulp.npmbox from gulp.

Thanks in advance.

**Comment by arei** [comment]
I was able to both `npmbox gulp` and `npmunbox gulp.npmbox` without issues using the latest (v2.1.1) version. Please try using that version.

**Comment by zongliangding** [comment]
Thanks.
