### ISSUE TITLE
Offline installation isn't working

### ISSUE THREAD

**Issue by YonatanKra** [arei/npmbox#24]
Hi,
I've followd the instructions up to this line:
```npm install --global --cache ./.npmbox.cache --optional --cache-min 99999 npmbox```
It does something (installs and the npmbox shows in my global node modules), but npmbox isn't working. From cmd I try: ```npmbox``` but it is undefined.
Any idea why?

**Comment by arei** [comment]
1). Is it possible your npm global node_modules isn't in your path some how? 

2). What OS are you using?

3). Can you run npmbox if you go to your global node_modules/.bin folder, where it should have an npmbox shell script?

4). Can your run the npm install command from your original post again, add the switch --verbose before the --global switch. Then cut and paste the entire output log in here?

**Comment by yccteam** [comment]
Hi,
Thanks a lot. I've found the issue.
As you suggested, I've checked the global env var in win.
I've found the batch files were created inside the "npm" folder itself and not inside the "npm/node_modules/npmbox" (nor the bin folder) for some reason.
I've added the correct path, and now it seems to work.
My problem now is this:
I've packed karma and jasmine. I'm now using ```npmunbox``` and it starts the process, but it shouts ```Error: Invalid version 0.0.0.1```.
Any idea why this happens? Might this be connected to the fact the batch runs from the npm folder?

**Comment by arei** [comment]
I doubt it is because "the batch runs from the npm folder". I will try to look at it tomorrow. In the meantime, any more specific logging information from you would be critical.  See instruction 4 above.  You can pass -verbose to npmunbox for more log detail.

**Comment by arei** [comment]
I had no problems doing Jasmine and Karma via npmbox and npmunbox. Please provide a log of the error message if you want me to look at this further.

**Comment by yccteam** [comment]
Hi,
I've recreated the npmbox files and it works like a charm.
Thanks a LOT!

**Comment by yccteam** [comment]
Ok, I have to reopen this.
My solution worked for a global install.
My problem starts when I try to unbox locally (npmunbox karma).
It throws this error: ```Error: Invalid Version [0.0.0.1]```
What does that mean?
Using ```--verbose``` doesn't add any more data.

**Comment by askumar** [comment]
Hi,
trying to do offline installation of npmbox 
on offline computer i did, tar -xvf  npmbox.npmbox and it created something like this
.npmbox.cache/xtend/4.0.0/package.tgz
.npmbox.cache/yauzl/
.npmbox.cache/yauzl/2.2.1/
...
after that i did 
npm install --global --cache ./.npmbox.cache --optional --cache-min 99999 npmbox
i get this 
npm http GET https://registry.npmjs.org/npmbox
npm http 200 https://registry.npmjs.org/npmbox
....
trying to pull from internet then it gave the error unable to connect the net.
Is there any thing i am missing or doing wrong.?
Thanks for help

**Comment by arei** [comment]
@askumar Please see #27 regarding the fix for this, in particular, adding ``--shrinkwrap false` to the npm command.

**Comment by arei** [comment]
@ycccteam I don't know what to tell you friend... `npmbox karma` and `npmunbox karma` both work fine for me. You can try upgrading to the new version (2.6.0) and see if that helps.

**Comment by arei** [comment]
Closing this. Please upgrading submit new issue if this persists.
