### ISSUE TITLE
Cannot untar npmbox.npmbox, even after removing " --no-same-owner --no-same-permissions"

### ISSUE THREAD

**Issue by alexeyismirnov** [arei/npmbox#30]
System: Ubuntu 14.04 LTS

After creating npmbox.npmbox, I am trying to untar it (on the same system, just as an experiment). Here is what I get:

```sh
alexey:~/npmbox$ tar -xvfz  ./npmbox.npmbox
tar: z: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
```

The solution is to remove "z", like this: `tar -xvf  ./npmbox.npmbox`. Then it works. Please fix the documentation .

**Comment by arei** [comment]
Added note in documentation.
