### ISSUE TITLE
Issues unboxing/installing

### ISSUE THREAD

**Issue by twodayslate** [arei/npmbox#32]
This is happening on my box without internet:  
without sudo: `Error: EACCESS mkdir '/usr/lib/node_modules' errno: 3`  
with sudo: `Error: getaddrinfo ENOTFOUND`

Using 2.6.1

**Comment by twodayslate** [comment]
Seems to just have been a problem with installing npmbox globally with npmbox. :\

**Comment by arei** [comment]
More than likely a permissions problem with your global folder.
