### ISSUE TITLE
npmbox for phantomjs

### ISSUE THREAD

**Issue by naveenbirru** [arei/npmbox#33]
I am facing an issue where phantomjs is fetching from CDN at the time of install everytime I build.

You have mentioned the following notes on the issue "npmunbox with multiple packages fails to install all packages ":

"Just a side note unrelated to this ticket, but I'm not sure how effective using npmbox will be with phnatomjs. The npm install process for phantomjs executes an install script that goes out to a CDN to fetch the latest version of phantomjs and stores it on its own. npmbox doesn't know anything about this cdn or the file retrieved from it. When you go to npmunbox phantomjs later, it's still going to make a network connection and try and get the cdn file. That's not really the spirit of npmbox and beyond the scope of what npm can do "

I am running into this exact issue.

Please let me if you have found any workaround for this issue?

**Comment by arei** [comment]
Yes, PhantomJS goes out during it install phase to download external runtime files and there is no way npmbox can help with that. Sorry.
