### ISSUE TITLE
Fix for offline install untar instructions

### ISSUE THREAD

**Issue by thatthatisis** [arei/npmbox#35]
There's a note about needing to remove the "f" in the tar command, but the real problem is that "-f" accepts an argument (the filename).

    4). Untar the .npmbox file. This will create the .npmbox.cache folder.
          tar -xvfz --no-same-owner --no-same-permissions npmbox.npmbox

This should help:
tar -xvzf npmbox.npmbox --no-same-owner --no-same-permissions

**Comment by arei** [comment]
I believe this is fixed in the readme.md already.
