### ISSUE TITLE
Unboxing ionic won't work

### ISSUE THREAD

**Issue by thisisgit** [arei/npmbox#38]
Hi, I'm trying to work with ionic framework but npmunbox throws an error.

It gives:
Error: getaddrinfo ENOTFOUND registry.npmjs.org
code: ' ENOTFOUND',
errno: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: ' registry.npmjs.org',
parent: 'ionic'

Any idea why this is happening?
Thanks in advance.

**Comment by arei** [comment]
It looks like ionic has an external dependency on node-gyp that it attempts to download at install time.  npmbox cannot handle these types of "third party" install requirements.  Sorry.
