### ISSUE TITLE
TypeError: Invalid non-string/buffer chunk]

### ISSUE THREAD

**Issue by amitsehgal** [arei/npmbox#40]
I have been trying to npmunbox private-bower and mocha on rhel 6 & 7 with node version v0.12.7 . Does anyone knows what is the issue ?  npmbox@2.7.0

npmunbox private-bower.npmbox

Unboxing private-bower.npmbox...
Unpacking private-bower...
  [TypeError: Invalid non-string/buffer chunk]

Same error with mocha
npmunbox mocha.npmbox

Unboxing mocha.npmbox...
Unpacking mocha...
  [TypeError: Invalid non-string/buffer chunk]

**Comment by Tiuser4567** [comment]
Above is a problem with the decompress lib (bug in versions earlier than 3.0.0, npmbox is using 2.3.0) https://github.com/kevva/decompress/issues/26 

workaround is to edit npmboxxer.js and in the tarExtract function, revert to using targz (the commented out code) and  comment out the decompress related code.

Need to update npmbox to use decompress v3.0.0+

**Comment by arei** [comment]
Pull Requests are always welcome!

**Comment by swetakadam** [comment]
wow this worked 
thanks @Tiuser4567

**Comment by arei** [comment]
Attempted to upgrade decompress to v3.0.0 for the npmbox 3.0.0 release.  However, I had some issues using decompress v3.0.0 and the documentation was a little lacking for my needs. Perhaps when I can do more of a deep dive I can do this upgrade.

**Comment by arei** [comment]
This is fixed in 3.1.0 as I removed the decompress library entirely and switched back to targz for extracting the files.
