### ISSUE TITLE
npm3 compatible installations?

### ISSUE THREAD

**Issue by markerikson** [arei/npmbox#41]
I'm currently running Node.js 5.0 with NPM 3.3.6.  If I run "npmbox some-package" and then "npmunbox some-package.npmbox", it appears that the installation process still installs everything in the old nested node_modules style.  

Skimming the code, it appears that npmbox uses NPM programmatically.  Is there a particular reason why this doesn't install in the newer deduped packages layout?  Any ideas for how to make that happen?

**Comment by markerikson** [comment]
Ah.  I think that npmbox gets its own copy of NPM, which appears to be 2.9.0.  Is there a good way to force it to use NPM@3 instead?

**Comment by arei** [comment]
The best way to make this happen would be to fork npmbox, fix the code, and then submit it back as a PR. :)

**Comment by arei** [comment]
Upgraded npm version in npmbox 3.0.0.
