### ISSUE TITLE
Fix for possible issue with offline installs

### ISSUE THREAD

**Issue by jgainfort** [arei/npmbox#42]
I, like some people who wrote previous issues, had problems trying to install packages offline using the suggested method.

Everytime I would try to npmubox <package> the following error would appear:

  { [Error: getaddrinfo ESRCH] code: 'ESRCH', errno: 'ESRCH', syscall: 'getaddrinfo' }

What I found that fixes this problem was to clear my npm cache before boxing and unboxing the desired package.

So on online machine:

npm cache clean
npmbox <package>

Offline machine:

npm cache clean
npmunbox <package>

Instead of posting this in every question that is open maybe this could be added to the README?

**Comment by arei** [comment]
Pull Request welcome.

**Comment by jgainfort** [comment]
@arei 

Ok, I can have one tomorrow.
