### ISSUE TITLE
npmbox dependencies with github reference in a restrictive environment

### ISSUE THREAD

**Issue by hbajaj2** [arei/npmbox#44]
I am planning to use npmbox/npmunbox in a restrictive environment with no access to internet. There are few dependencies which are referring to Github and npmunbox fails. How can I use npmbox to package Github/bitbucket references, so that i can use it to unbox on restriction environment.

Thanks,
Sunny

**Comment by mobinni** [comment]
We had a similar request, however the developer stated in a tweet that this is not possible.
We decided to go with npm pack instead and run npm install/rebuild on those packed folder again. Seems to work.
