### ISSUE TITLE
Seems to have trouble working with tfs-cli

### ISSUE THREAD

**Issue by jlongo62** [arei/npmbox#47]
tfs-cli is the TFS cross platform client. Microsoft abandoned tf.exe to use tfx commands via node. Unfortunately , many environments prevent internet access or mess with it. npmbox sounds like the perfect solution for this; however it seems to fail when unboxing.

Steps: 
1) Install tfs-cli:
npm install -g tfx-cli
2) run npmbox tfs-cli
3) uninstall tfs-cli
npm uninstall -g tfx-cli
4) attempt reinstall: 
npmunbox tfs-cli.nomunbox

The failure occurs with a path reference.

**Comment by arei** [comment]
1). I had no problem using npmbox and npmunbox with tfx-cli with v0.10.36 or v5.9.0 of node.

2). Could you please execute npmbox and npmunbox with the -v switch and paste the logs here?

3). My test was this if you want to duplicate:

`npmbox tfx-cli`
(disable all network connections)
`npmunbox tfx-cli`

**Comment by arei** [comment]
Closing this. Please upgrading submit new issue if this persists.
