### ISSUE TITLE
npmbox --help has incorrect long arguments and description text.

### ISSUE THREAD

**Issue by adamonline45** [arei/npmbox#50]
The output of `npmbox --help` has two issues:

First, an incorrect description for the -s option. It presently says _"Shows additional output which is normally hidden,"_ and should instead say something to the opposite effect, such as _"Suppresses all output"_ or similar, as appropriate (I don't know, it might still print errors).

Second, the `-silent` and `-verbose` long-form options should read `--silent` and `--verbose`, with two dashes each.

Thanks for your work!

**Comment by arei** [comment]
Fixed. Thank you for your bug request.
