### ISSUE TITLE
Feature request: npmunbox --install command

### ISSUE THREAD

**Issue by adamonline45** [arei/npmbox#51]
Feature request: an `npmunbox --install <path>` command.

**Our situation:**

We are offline, but with access to online machines for initial grabbing of .npmbox files.

I have a project that I just pulled down. It has a number of dependencies, listed in package.json.

In a normal, online environment, I could just do `npm install` and it would install all the dependencies for me.

Using npmbox, I need to do one at a time, and I need to reference package.json to get the complete list.

**My suggestion:**

An `npmunbox --install <path>` command, that will install from `<path>`, the npmboxes of any packages which are specified in package.json.

**Why this would be useful:**

This would allow us to maintain a network location or USB drive of npmboxes, and allow rapid deployment to new machines.

We have not had great luck with running alternative package managers such as sinopia. Npmbox works well for us, but it is tedious to get a project set up on a new machine.

Thanks!

**Comment by arei** [comment]
I don't think I understand this feature request.  Could you be much more specific? what problem are you trying to address? How does adding `--install` address that?

**Comment by adamonline45** [comment]
@arei, I have revised my original post. Thanks :)

**Comment by arei** [comment]
I'm not trying to be difficult, but the entire purpose of npmbox is to download an install and all of its dependencies. For example, if I do an `npmbox npmbox` the resulting tar file will contain not just the npmbox package, but all of its dependencies as well.  Doing an `npmunbox npmbox` on the other side installs npmbox and all the dependencies as if you had issued a `npm install npmbox` command.

Is that not what you are describing?

**Comment by adamonline45** [comment]
I appreciate your persistence in understanding me! I am not trying to be difficult either :) Let me try to explain better. Please forgive me if I sound terse or condescending, I only intend to be clear:

First let me establish, I am not talking about dependencies on a package that has been npmbox'd. I know that npmbox handles those, and it does it very well! For the sake of this conversation, when I mention dependencies, I am talking about the dependencies in *my project*, as listed in package.json.

So, consider we have an established project, and I'm setting up a new dev machine, or deploying the project. Our project has a dozen dependencies on other npm packages. (Again, let's not discuss the dependencies of our project's immediate dependencies, let's just trust they are handled implicitly).

In an online environment, I can run `npm install` and it will go through my project's immediate dependencies, as listed in package.json, and install them (and their dependencies--but again, not relevant at a high level).

In an offline environment, using npmbox, I have to run npmunbox for each dependency within my project. I am merely suggesting a shortcut, `npmunbox --install <path_to_folder_of_npmbox_files>`, so one can npmunbox all the dependencies listed in package.json. Yes, that includes the dependencies of those dependencies, but again, the matter here is the shortcut.

I appreciate your patience!  I hope this is more clear. If not, I'll be glad to try again :)

**Comment by arei** [comment]
I understand the request now, thank you.  That said, I don't see myself having much time to work on this.  Pull requests always welcome.  If you do submit one, please make sure not to change the underlying functionality of npmbox.

**Comment by reubent** [comment]
I have a grunt task that does this (and the boxing...). I'll see if I can get permission to open source it.

**Comment by frogred8** [comment]
I am asking you to confirm that PR 3 months ago is still pending.
That feature is required to me.

**Comment by danfuzz** [comment]
Fixed in v4.2.0, just published.
