### ISSUE TITLE
npm install --global --cache fail can you help me

### ISSUE THREAD

**Issue by fhqdgv** [arei/npmbox#52]
npm install --global --cache .\.npmbox.cache --optional --cache-min 99999 --sh                                                                                                                                                             rinkwrap false npmbox

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   '--cache',
1 verbose cli   '..npmbox.cache',
1 verbose cli   '--optional',
1 verbose cli   '--cache-min',
1 verbose cli   '99999',
1 verbose cli   '--shrinkwrap',
1 verbose cli   'false',
1 verbose cli   'npmbox' ]
2 info using npm@3.6.0
3 info using node@v5.7.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData npmbox
8 silly fetchNamedPackageData npmbox
9 silly mapToRegistry name npmbox
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/npmbox
13 verbose request uri https://registry.npmjs.org/npmbox
14 verbose request no auth needed
15 info attempt registry request try #1 at 10:10:17
16 verbose request id 62114a1fcbf591dc
17 http request GET https://registry.npmjs.org/npmbox
18 info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
19 info attempt registry request try #2 at 10:10:27
20 http request GET https://registry.npmjs.org/npmbox
21 info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
22 info attempt registry request try #3 at 10:11:27
23 http request GET https://registry.npmjs.org/npmbox
24 silly fetchPackageMetaData Error: getaddrinfo ENOENT registry.npmjs.org:443
24 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:856:11)
24 silly fetchPackageMetaData     at errnoException (dns.js:31:15)
24 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
24 silly fetchPackageMetaData  error for npmbox { [Error: getaddrinfo ENOENT registry.npmjs.org:443]
24 silly fetchPackageMetaData   code: 'ENOENT',
24 silly fetchPackageMetaData   errno: 'ENOENT',
24 silly fetchPackageMetaData   syscall: 'getaddrinfo',
24 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
24 silly fetchPackageMetaData   host: 'registry.npmjs.org',
24 silly fetchPackageMetaData   port: 443 }
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Starting
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: getaddrinfo ENOENT registry.npmjs.org:443
30 verbose stack     at Object.exports._errnoException (util.js:856:11)
30 verbose stack     at errnoException (dns.js:31:15)
30 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
31 verbose cwd H:\node\off
32 error Windows_NT 10.0.10586
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "--cache" "..npmbox.cache" "--optional" "--cache-min" "99999" "--shrinkwrap" "false" "npmbox"
34 error node v5.7.0
35 error npm  v3.6.0
36 error code ENOENT
37 error errno ENOENT
38 error syscall getaddrinfo
39 error enoent getaddrinfo ENOENT registry.npmjs.org:443
40 error enoent getaddrinfo ENOENT registry.npmjs.org:443
40 error enoent This is most likely not a problem with npm itself
40 error enoent and is related to npm not being able to find a file.
41 verbose exit [ 1, true ]

**Comment by arei** [comment]
It appears like your --cache argument is not correct.  Best answer I can give you.  Sorry.

**Comment by ackerleytng** [comment]
I realised I installed node 0.6.5 instead of node 6.5.

With node 6.5 and npm 3.10.3, I was able to install npmbox with the provided instructions.
