### ISSUE TITLE
npmunbox terminates unfinished with big archives

### ISSUE THREAD

**Issue by danme** [arei/npmbox#54]
The **tar.gz** module has an issue with big files in version **1.0.5**.
It just terminates the running program (after printing "Unpacking..."), leaving a uncompleted extract folder .npmbox-cache in the current directory.

Can be reproduced on a Ubuntu 14.04 32-bit (node 6.2.2):
```bash
npmbox protobufjs
npmunbox protobufjs
```

Please downgrade the dependency **tar.gz** to **1.0.2**.

**Comment by danme** [comment]
https://github.com/alanhoff/node-tar.gz/issues/38

**Comment by arei** [comment]
Fixed in 4.0.0.
