### ISSUE TITLE
npmbox repeatedly tries to load fsevents optional dependency from registry

### ISSUE THREAD

**Issue by reubent** [arei/npmbox#55]
Many packages have an optional dependency to fsevents, a package that only works on MacOS. When I box these packages on a Linux host, it hence doesn't include the package.

When I deploy the boxed package to my CI server which has no network access, it tries repeatedly to fetch the package from registry.npmjs.org (which would tell it not to install as wrong arch) which causes it to hang for quite a while as it can't open a connection.

```
npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN network connect ETIMEDOUT 151.101.60.162:443
npm WARN optional Skipping failed optional dependency /watchify/chokidar/fsevents:
npm WARN network connect ETIMEDOUT 151.101.60.162:443
```

Is there either a way to either package in the optional dep when we box or to make it not go to registry for optional dependencies?

**Comment by arei** [comment]
Unfortunately, no, it is not possible for npmbox to bundle externally installed dependencies such as fsevents uses. This is a known limitation with solutions like npmbox.
