### ISSUE TITLE
install npmbox on offline windows7 system fail

### ISSUE THREAD

**Issue by fhqdgv** [arei/npmbox#57]
npm install --global --cache .\.npmbox.cache --optional --cache-min 99999 --shrinkwrap false npmbox
error
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   '--cache',
1 verbose cli   '..npmbox.cache',
1 verbose cli   '--optional',
1 verbose cli   '--cache-min',
1 verbose cli   '99999',
1 verbose cli   '--shrinkwrap',
1 verbose cli   'false',
1 verbose cli   'npmbox' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose install initial load of C:\Users\Administrator\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\Administrator\AppData\Roaming\npm\package.json
6 silly cache add args [ 'npmbox', null ]
7 verbose cache add spec npmbox
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'npmbox',
8 silly cache add   scope: null,
8 silly cache add   name: 'npmbox',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed npmbox@latest
10 verbose addNamed "latest" is being treated as a dist-tag for npmbox
11 info addNameTag [ 'npmbox', 'latest' ]
12 silly mapToRegistry name npmbox
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'npmbox',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'npmbox',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.org/npmbox
17 verbose addNameTag registry:https://registry.npmjs.org/npmbox not in flight; fetching
18 verbose request uri https://registry.npmjs.org/npmbox
19 verbose request no auth needed
20 info attempt registry request try #1 at 11:35:35
21 verbose request id 0814347d078485a0
22 http request GET https://registry.npmjs.org/npmbox
23 info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
24 info attempt registry request try #2 at 11:35:45
25 http request GET https://registry.npmjs.org/npmbox
26 info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
27 info attempt registry request try #3 at 11:36:45
28 http request GET https://registry.npmjs.org/npmbox
29 verbose stack Error: getaddrinfo ENOENT registry.npmjs.org:443
29 verbose stack     at Object.exports._errnoException (util.js:873:11)
29 verbose stack     at errnoException (dns.js:32:15)
29 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
30 verbose cwd E:\auto\box
31 error Windows_NT 6.1.7601
32 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "--cache" "..npmbox.cache" "--optional" "--cache-min" "99999" "--shrinkwrap" "false" "npmbox"
33 error node v4.4.7
34 error npm  v2.15.8
35 error code ENOENT
36 error errno ENOENT
37 error syscall getaddrinfo
38 error enoent getaddrinfo ENOENT registry.npmjs.org:443
38 error enoent This is most likely not a problem with npm itself
38 error enoent and is related to npm not being able to find a file.
39 verbose exit [ 1, true ]

**Comment by arei** [comment]
Please check the reference to the npmbox cache file.  It looks like you referenced `..npmbox.cache` when you probably wanted `..\npmbox.cache` or something similar.

**Comment by fhqdgv** [comment]
i think .npmbox.cache folder it's ok. it come from
1.npm install -g npmbox
2.npmbox npmbox  // copy npmbox.npmbox to offline system
3.tar --no-same-owner --no-same-permissions -xvzf npmbox.npmbox
last:
npm install --global --cache .\.npmbox.cache --optional --cache-min 99999 --shrinkwrap false npmbox
so i don't know what has gone wrong.
