### ISSUE TITLE
npmbox offline install 

### ISSUE THREAD

**Issue by TheoTsatsos** [arei/npmbox#65]
Hi @arei,

I am quite new to npm and I would really aprreciate your  #help. I want to install npmbox on an offline 2008 windows server. I followed the instructions until:
npm install --global --cache .\.npmbox.cache --optional --cache-min 99999 --shrinkwrap false npmbox

but I get: 
npm ERR! network connect ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "--cache" ".\\.npm
box-cache" "--optional" "--cache-min" "99999" "--shrinkwrap" "false" "npmbox"
npm ERR! cwd G:\bamboo\build-dir\917505\CI-TDSCI-JOB1\Dev\DHWebApps\SingleDealer
Platform\Code
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! syscall connect
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     G:\bamboo\build-dir\917505\CI-TDSCI-JOB1\Dev\DHWebApps\SingleDealer
Platform\Code\npm-debug.log
npm ERR! not ok code 0

I read that the --shrinkwrap false flag should fix the issue but it didn't.

Any suggestions?

PS: I did the first steps on my local online machine as suggested in the instructions, and then I ciopied over the npmbox.npmbox file.
Thank you in advance

**Comment by arei** [comment]
1). Make sure your read this section of the readme: https://github.com/arei/npmbox#common-problems

2). Looks,like you are running a really old version of npm (and node). Try upgrading? If you cannot upgrade, try this version of the command from a few years ago: `npm install --global --cache ./.npmbox-cache --optional --no-registry --fetch-retries 0 --fetch-retry-factor 0 --fetch-retry-mintimeout 1 --fetch-retry-maxtimeout 2 npmbox`

3). Copy the npm-debug.log file and paste it here if you can.

**Comment by TheoTsatsos** [comment]
I tried this command and still nothing..

Debug:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'local-npmbox' ]
2 info using npm@1.4.28
3 info using node@v0.10.33
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose cache add [ 'local-npmbox', null ]
6 verbose cache add name=undefined spec="local-npmbox" args=["local-npmbox",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'local-npmbox',
7 verbose parsed url   path: 'local-npmbox',
7 verbose parsed url   href: 'local-npmbox' }
8 silly lockFile 3977ff63-local-npmbox local-npmbox
9 verbose lock local-npmbox C:\Users\s-dv-dhb-app\AppData\Roaming\npm-cache\3977ff63-local-npmbox.lock
10 silly lockFile 3977ff63-local-npmbox local-npmbox
11 silly lockFile 3977ff63-local-npmbox local-npmbox
12 verbose addNamed [ 'local-npmbox', '' ]
13 verbose addNamed [ null, '*' ]
14 silly lockFile 31978af9-local-npmbox local-npmbox@
15 verbose lock local-npmbox@ C:\Users\s-dv-dhb-app\AppData\Roaming\npm-cache\31978af9-local-npmbox.lock
16 silly addNameRange { name: 'local-npmbox', range: '*', hasData: false }
17 verbose request where is /local-npmbox
18 verbose request registry https://registry.npmjs.org/
19 verbose request id 77c2ae4fe61fa490
20 verbose url raw /local-npmbox
21 verbose url resolving [ 'https://registry.npmjs.org/', './local-npmbox' ]
22 verbose url resolved https://registry.npmjs.org/local-npmbox
23 verbose request where is https://registry.npmjs.org/local-npmbox
24 info trying registry request attempt 1 at 12:36:29
25 http GET https://registry.npmjs.org/local-npmbox
26 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
27 info trying registry request attempt 2 at 12:37:00
28 http GET https://registry.npmjs.org/local-npmbox
29 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
30 info trying registry request attempt 3 at 12:38:21
31 http GET https://registry.npmjs.org/local-npmbox
32 silly lockFile 31978af9-local-npmbox local-npmbox@
33 silly lockFile 31978af9-local-npmbox local-npmbox@
34 error network connect ETIMEDOUT
34 error network This is most likely not a problem with npm itself
34 error network and is related to network connectivity.
34 error network In most cases you are behind a proxy or have bad network settings.
34 error network
34 error network If you are behind a proxy, please make sure that the
34 error network 'proxy' config is set properly.  See: 'npm help config'
35 error System Windows_NT 6.1.7600
36 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "local-npmbox"
37 error cwd G:\bamboo\build-dir\917505\CI-TDSCI-JOB1\Dev\DHWebApps\SingleDealerPlatform\Code
38 error node -v v0.10.33
39 error npm -v 1.4.28
40 error syscall connect
41 error code ETIMEDOUT
42 error errno ETIMEDOUT
43 verbose exit [ 1, true ]

**Comment by arei** [comment]
That npm-debug.log is for a different command. Can you post the one from the execution of recommended command?

**Comment by TheoTsatsos** [comment]
sorry about that

I just updated node to version 6.5.0 and npm to 3.10.3

I run the "new command":
npm install --global --cache .\.npmbox.cache --optional --cache-min 99999 --shrinkwrap false npmbox

and my error message is:
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 151.101.16.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     G:\bamboo\build-dir\917505\CI-TDSCI-JOB1\Dev\DHWebApps\SingleDealer
Platform\Code\npm-debug.log


and the npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   '--cache',
1 verbose cli   '.\\.npmbox.cache',
1 verbose cli   '--optional',
1 verbose cli   '--cache-min',
1 verbose cli   '99999',
1 verbose cli   '--shrinkwrap',
1 verbose cli   'false',
1 verbose cli   'npmbox' ]
2 info using npm@3.10.3
3 info using node@v6.5.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData npmbox
8 silly fetchNamedPackageData npmbox
9 silly mapToRegistry name npmbox
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'npmbox',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'npmbox',
12 silly mapToRegistry   name: 'npmbox',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/npmbox
14 verbose request uri https://registry.npmjs.org/npmbox
15 verbose request no auth needed
16 info attempt registry request try #1 at 1:19:24 PM
17 verbose request id ac6087683f4f9897
18 http request GET https://registry.npmjs.org/npmbox
19 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.16.162:443
20 info attempt registry request try #2 at 1:19:55 PM
21 http request GET https://registry.npmjs.org/npmbox
22 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.16.162:443
23 info attempt registry request try #3 at 1:21:16 PM
24 http request GET https://registry.npmjs.org/npmbox
25 silly fetchPackageMetaData Error: connect ETIMEDOUT 151.101.16.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1026:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1049:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
25 silly fetchPackageMetaData  error for npmbox { Error: connect ETIMEDOUT 151.101.16.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1026:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1049:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
25 silly fetchPackageMetaData   code: 'ETIMEDOUT',
25 silly fetchPackageMetaData   errno: 'ETIMEDOUT',
25 silly fetchPackageMetaData   syscall: 'connect',
25 silly fetchPackageMetaData   address: '151.101.16.162',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: connect ETIMEDOUT 151.101.16.162:443
31 verbose stack     at Object.exports._errnoException (util.js:1026:11)
31 verbose stack     at exports._exceptionWithHostPort (util.js:1049:20)
31 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
32 verbose cwd G:\bamboo\build-dir\917505\CI-TDSCI-JOB1\Dev\DHWebApps\SingleDealerPlatform\Code
33 error Windows_NT 6.1.7600
34 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "--cache" ".\\.npmbox.cache" "--optional" "--cache-min" "99999" "--shrinkwrap" "false" "npmbox"
35 error node v6.5.0
36 error npm  v3.10.3
37 error code ETIMEDOUT
38 error errno ETIMEDOUT
39 error syscall connect
40 error network connect ETIMEDOUT 151.101.16.162:443
41 error network This is most likely not a problem with npm itself
41 error network and is related to network connectivity.
41 error network In most cases you are behind a proxy or have bad network settings.
41 error network
41 error network If you are behind a proxy, please make sure that the
41 error network 'proxy' config is set properly.  See: 'npm help config'
42 verbose exit [ 1, true ]

**Comment by arei** [comment]
For whatever reason, npm is not seeing the .npmbox-cache folder. Perhaps it's a permissions problem, perhaps something else? 

Is your G drive a network map?

Are there any other folders or files in the directory with .npmbox-cache in it?

Did you untar npm box.npmbox correctly? If so there should be a .npmbox-cache folder and a handful of single package names like "npmbox" with no extension. (Just covering the bases here.)

If there is a npmbox file with no extension, delete it and try again.

**Comment by TheoTsatsos** [comment]
I managed to install it (I think)

This is the output:
c:\Users\s-dv-dhb-app\Desktop>npm install --global --cache .npmbox.cache --optio
nal --cache-min 99999 --shrinkwrap false npmbox
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install th
e latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use
@segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher
to avoid a RegExp DoS issue
C:\Users\s-dv-dhb-app\AppData\Roaming\npm\npmunbox -> C:\Users\s-dv-dhb-app\AppD
ata\Roaming\npm\node_modules\npmbox\bin\npmunbox
C:\Users\s-dv-dhb-app\AppData\Roaming\npm\npmbox -> C:\Users\s-dv-dhb-app\AppDat
a\Roaming\npm\node_modules\npmbox\bin\npmbox
C:\Users\s-dv-dhb-app\AppData\Roaming\npm
`-- npmbox@4.0.1


Now that means that I can run the npmbox commands?

i.e npmunbox grunt.npmbox

Or there is some other procedure I have to follow?

**Comment by arei** [comment]
What did you do that got it installed? How did you fix it?

Yes, you should be able to use npmbox and npmunbox from the command line now, although I would not try running npmunbox on npmbox again as it's already installed.

**Comment by TheoTsatsos** [comment]
under **C:\Users\username\AppData\Roaming** I only have the **npm** folder and I am missing the **npm-cache one**. (I compared it to the installation in my local pc)

I did not use the npmbo.npmbox file given by the developer, I produced mine using the: **npm  install -gnpmbox**

Although it seems to be ok-ish. When I eun **npmunbox grunt.npmbox** it tries to connect to the internet and because the box is offline it finally fails.

How can i fix that?

**Comment by TheoTsatsos** [comment]
Hi @arei,

this is still not working...

Could you advise please?
