### ISSUE TITLE
New `npmunbox` option: `--scripts`

### ISSUE THREAD

**Issue by danfuzz** [arei/npmbox#79]
I noticed that `npmunbox` runs the underlying `npm install` with scripts disabled. I'm guessing this was done because it's common for scripts to try to use the network. However, I'd at least like the option of letting scripts run.

I suggest adding a `--scripts` option which would let this happen.

**Comment by danfuzz** [comment]
Fixed in v4.2.0, just published.

**Comment by dtgriscom** [comment]
I'm a little confused about this option, or rather that the default has been *not* to run scripts. About 1% of scripts in an extremely un-scientific sampling depend on the `"install"` script to finish installation, which means the default `npmunbox` command would fail, perhaps subtly, in these situations. Examples I found: `dtrace-provider`, and `snmpjs`.

What would the downside be to run scripts on unboxing by default?

**Comment by danfuzz** [comment]
Speaking as the original reporter, I'd be perfectly happy if the default were changed. I made the request as stated, though, because not running scripts _is_ the status quo and so it would be a backward-incompatible change in behavior. That said, maybe it's reasonable to switch the default as long as it's done with a major version bump.

**Comment by dtgriscom** [comment]
I'll file this as a feature request, and we'll see if the lead developer objects.
