### ISSUE TITLE
npm packages with fwd slash = kaboom

### ISSUE THREAD

**Issue by ricksbrown** [arei/npmbox#86]
The following command will cause npmbox to clutch its chest and fall to the ground gasping:

```npmbox "@types/chai@3.4.34"```

I had the same reaction when I discovered that NPM modules are allowed to include a forward slash in their name 😱 

I patched my local install by changing [line 343](https://github.com/arei/npmbox/blob/671354ae4304745e2974445c19e9a068aa49d98a/npmboxxer.js#L343) from this: 
```if (!target) setTarget(npa(source).name);```
to this:
```if (!target) setTarget(npa(source).escapedName);```

I did not think it through beyond "works for me". 
Happy to open a PR for that if you like.

**Comment by arei** [comment]
Yes! Please submit a PR and receive the fabulous reward of our gratitude and free beer if we are ever in the same city at the same time.
